load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# golang
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "099a9fb96a376ccbbb7d291ed4ecbdfd42f6bc822ab77ae6f1b5cb9e914e94fa",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.19.1")

http_archive(
    name = "bazel_gazelle",
    sha256 = "448e37e0dbf61d6fa8f00aaa12d191745e14f07c31cabfa731f0c8e8a4f41b97",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.28.0/bazel-gazelle-v0.28.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.28.0/bazel-gazelle-v0.28.0.tar.gz",
    ],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

# docker
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "b1e80761a8a8243d03ebca8845e9cc1ba6c82ce7c5179ce2b295cd36f7e394bf",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.25.0/rules_docker-v0.25.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load(
    "@io_bazel_rules_docker//container:pull.bzl",
    "container_pull",
)

container_pull(
    name = "python",
    architecture = "amd64",
    digest = "sha256:eef39ed128b235c95c723eabe2de05670ba87f3273cc784effe4c3d9d0847c09",
    registry = "docker.io",
    repository = "python",
)

# python_docker
local_repository(
    name = "rules_python_docker",
    path = "..",
)

local_repository(
    name = "pip_overrides",
    path = "overrides",
)

load("@rules_python_docker//:defs.bzl", "pip_import")

# pip_monorepo
pip_import(
    name = "pip_monorepo",
    container_overrides = {
        "@pip_overrides//python/psycopg2-binary": "psycopg2-binary",
        "@pip_overrides//python/xxhash": "xxhash",
    },
    requirements = "//:requirements.in",
    requirements_lock = "//:requirements_lock.txt",
)

load("@pip_monorepo_host//:requirements.bzl", pip_monorepo_host_pip_install = "pip_install")

pip_monorepo_host_pip_install([
    "--only-binary",
    ":all",
])

load("@pip_monorepo_container//:requirements.bzl", pip_monorepo_container_pip_install = "pip_install")

pip_monorepo_container_pip_install([
    "--only-binary",
    ":all",
])

# pip_hello_world_custom
pip_import(
    name = "pip_hello_world_custom",
    container_overrides = {
        "@pip_overrides//python/psycopg2-binary": "psycopg2-binary",
        "@pip_overrides//python/xxhash": "xxhash",
    },
    requirements = "//:requirements.in",
    requirements_lock = "//:requirements_lock.txt",
)

load("@pip_hello_world_custom_host//:requirements.bzl", pip_hello_world_custom_host_pip_install = "pip_install")

pip_hello_world_custom_host_pip_install([
    "--only-binary",
    ":all",
])

load("@pip_hello_world_custom_container//:requirements.bzl", pip_hello_world_custom_container_pip_install = "pip_install")

pip_hello_world_custom_container_pip_install([
    "--only-binary",
    ":all",
])
