local_repository(
    name = "rules_python_docker",
    path = "..",
)

load("@rules_python_docker//:defs.bzl", "pip_import")

pip_import(
    name = "product",
    requirements = "//:requirements.in",
    requirements_lock = "//:requirements_lock.txt",
)
